### PR TITLE
Set max SDK version to <3.0.0

### PR DESCRIPTION
**Pull request by scheglov**
And a couple of other clean-ups.

### CODE REVIEW

**Review by bwilkerson — APPROVED** [review]

**Comment by kevmoo** [comment]
Woah...aren't we duping #16 ?

**Comment by scheglov** [comment]
Hm... #16 is an issue, this is a PR, where is a duplication?

**Comment by kevmoo** [comment]
er, sorry - #17

**Comment by scheglov** [comment]
Ah, yes.
OK, #17 looks good.

**Comment by bwilkerson** [comment]
But #17 missed some of the cleanup in #18, unless I missed something.

**Pull request closed without merging**
